### ISSUE TITLE
IntelliJ 2016.1 creates separate module for generated querydsl classes

### ISSUE THREAD

**Issue by TheKojuEffect** [ewerk/gradle-plugins#40] opened 2016-03-23 03:32 UTC
It looks like IntelliJ 2016.1 creates separate modules based on directory structure. When the `querydslSourcesDir` is set to `src/querydsl/java`, it creates a separate module `querydsl` and it shows errors in editor showing `Class not found` in main java source files.

https://blog.jetbrains.com/idea/2016/03/intellij-idea-2016-1-is-here/
http://mrhaki.blogspot.com/2016/03/gradle-goodness-source-sets-as-intellij.html

**Comment by TheKojuEffect** [comment] 2016-03-23 04:06
I think it is related to intellij gradle plugin. Closing this.

**Comment by The-Crocop** [comment] 2016-03-23 11:57
Im struggling with the same Problem. What can we do here?

**Comment by holgerstolzenberg** [comment] 2016-03-23 12:11
Well I am still on IntelliJ 15 and could not try. As nothing changed with the plugins, I think it is related to IntelliJ-16. You should file an issue there, maybe @TheKojuEffect already did.

It would be fine to cross-reference the created IntelliJ ticket here.

**Comment by corneil** [comment] 2016-03-23 12:17
I have a project with Gradle and the plugin `com.ewerk.gradle.plugins.querydsl`
I didn't have to do anything special for it to work as expected. Java classes and test classes both use the querydsl generated artifacts and no classpath errors.

It may be worthwhile reloading the Gradle project in the new version of IntelliJ or enable auto-import on Gradle projects.

**Comment by TheKojuEffect** [comment] 2016-03-23 16:38
Hi @corneil, Would it be appropriate to share your querydsl gradle settings with Intellij 2016.1? Reloading gradle project and enabling auto-import isn't helping.

**Comment by TheKojuEffect** [comment] 2016-03-23 17:04
I think following IntelliJ Idea tickets are related to this issue.

https://youtrack.jetbrains.com/issue/IDEA-153541
https://youtrack.jetbrains.com/issue/IDEA-153485
https://youtrack.jetbrains.com/issue/IDEA-149753
https://youtrack.jetbrains.com/issue/IDEA-150042

**Comment by corneil** [comment] 2016-03-23 21:26
I have a test project that I updated to Gradle 2.12 and did a fresh import into IntelliJ 2016.1

[https://github.com/corneil/spring-data-demo](https://github.com/corneil/spring-data-demo)

In order to execute a unit test in IntelliJ:
* Find `org.springframework.data.querydsl.demo.test.AllTests` in sub project `spring-data-querydsl-demo`
* Create a run configuration and add one of the profiles like `-Dspring.profiles.active=jpa-hibernate`

You will notice I had to add:
```gradle
sourceSets {
    main {
        output.resourcesDir = output.classesDir
    }
}
```
This is to solve a problem with JPA/Hibernate and isn't new to the current version of Gradle or IntelliJ.

**Comment by The-Crocop** [comment] 2016-03-24 05:51
Are you usng the QClasses in that project?
Thats the thing thats not working for me

**Comment by corneil** [comment] 2016-03-24 06:28
The `spring-data-querydsl-demo` subproject specifically demonstrates Q classes.

**Comment by The-Crocop** [comment] 2016-03-24 07:32
Ah ok thank you I will check it out later

**Comment by holgerstolzenberg** [comment] 2016-03-24 09:17
I´ll reopen the issue for the moment but I still think that this is not related to the plugins.

**Comment by corneil** [comment] 2016-03-24 10:51
@The-Crocop do you have a sample project that reproduces the problem?

**Comment by TheKojuEffect** [comment] 2016-03-24 13:18
Hey @corneil, Thanks but same problem with your demo project. There were errors in your service impl classes.

**Comment by The-Crocop** [comment] 2016-03-24 14:28
Hi I basically have a jhipster project where I tried to add querydsl

**Comment by griffio** [comment] 2016-03-30 11:20
I think IDEA-152581 is the latest update to this to track,
Option to have merged modules where the sourceSets are co-located in the original module.

https://youtrack.jetbrains.com/issue/IDEA-152581#tab=Comments
and https://youtrack.jetbrains.com/issue/IDEA-153231

**Comment by TheKojuEffect** [comment] 2016-04-01 05:39
https://youtrack.jetbrains.com/issue/IDEA-150685 was resolved but this is not yet fixed in 2016.1.1 update.

**Comment by holgerstolzenberg** [comment] 2016-04-18 07:48
Any updates on this? I am not on 16 by now, can anyone please verify if the problem is still present?

**Comment by griffio** [comment] 2016-04-18 08:43
Looks like there is an update.

I downloaded the latest IDEA EAP Version (Build #IU-145.969, built on April 13, 2016).

There is now a new option under Gradle - builds -  **create separate module per source set.**

**Uncheck** this option and it will flatten the modules and seems to work as previous behaviour.

I tried it on my "spring data hopper" test project and works ok. Reloading the gradle build will remove any extra modules.

**Comment by holgerstolzenberg** [comment] 2016-04-22 14:44
As @griffio explained, I think there is no need to keep this one open. Will close it.

**Comment by corneil** [comment] 2016-05-04 15:38
@TheKojuEffect I didn't see your comment about the problems with service impl classes. Can you provide more info? Are you on the latest version?

**Comment by griffio** [comment] 2016-06-30 13:47
@holgerstolzenberg 
Using - both IntelliJ IDEA (Community Edition) 2016.1 and latest 2016.2 EAP and **unchecked - create separate module per source set**

"gradle-plugins-samples" - integration java is shown as **java source** and not _test source_ as per internal plugin configuration. 

So yes, confirmed, it's not behaving as per Intellij15.

There must be some incompatibility between Intellij and Gradle API now. Will have to see if any issues.

**Comment by griffio** [comment] 2016-07-08 00:42
@holgerstolzenberg 

Looks like nebula.integtest plugin just leans on the "idea" plugin dsl internally to setup test folders.

When using **unchecked - create separate module per source set** for importing a gradle project, add the snippet below to the "ewerk sample" project and it should flag the "integration" directory as test sources. Could be added internally to the plugin as a work-around. 
~~~
plugins {
    id 'idea'
}
...
idea {
    module {
        testSourceDirs += file('src/integration/java')
        scopes.TEST.plus += [configurations.integrationCompile, configurations.integrationRuntime]
   }
}
~~~

**Comment by holgerstolzenberg** [comment] 2016-07-08 07:58
Hey @griffio,

well I already thought about it but rejected it in the end. We would violate one of the biggest build system rule out there "Be IDE independent". I do not like to have Idea specific stuff in my build, the more we should not rely on that in the plugins. It would need to detect which IDE is used and so on...

It worked with IntelliJ 15 so it should be possible. I think we should file a bug at the IntelliJ repo to get this feature back.

**Comment by thekalinga** [comment] 2016-10-14 04:54
Hi,

Is there any update on this?

**Comment by jchen9shc** [comment] 2016-10-18 23:45
I run into the same issue, can't use these Q classes in test, any solution here?

**Comment by griffio** [comment] 2016-10-19 07:39
Hi @jchen9shc,  

Not a the moment - current work arounds are listed above:-

 a. unchecked - create separate module per source set 
 b. Add some gradle script to your project to configure test classpath

You can check https://youtrack.jetbrains.com/issue/IDEA-151925 for info.

Regards,

@griffio

**Comment by holgerstolzenberg** [comment] 2016-10-19 08:03
Workaround [a] (separate module sets) definitively is working.

**Comment by joakimgottzen** [comment] 2016-10-26 11:20
One way to handle this is by allowing the configuration to override the source set name, i.e. being able to set it to 'main'. I completely agree that the plugin should be IDE-agnostic, but allowing customization to accommodate specific IDEs would not be an issue I hope.

Meanwhile, the following should solve it without disabling the default IntelliJ setting:
```Gradle
sourceSets {
    main {
        java {
            srcDir "$buildDir/generated-sources/apt"
        }
    }
}

querydsl {
    querydslSourcesDir = "$buildDir/generated-sources/apt"
}
```

**Comment by jchen9shc** [comment] 2016-11-07 22:06
@joakimgottzen , thank you very much. I like this way and don't want to mess with IntelliJ setting.

**Closed** 2017-04-07 08:49 UTC
Labels: help wanted, question
