### ISSUE TITLE
Run/Debug is broken with latest Idea 2016.1 and gradle 2.12 releases 

### ISSUE THREAD

**Issue by ieugen** [ewerk/gradle-plugins#41] opened 2016-03-23 13:29 UTC
Hello, 

I have gradle 2.12 and Idea 2016.1 and use querydsl plugin. After the update things don't work as expected. 

The new gradle-idea integration create an idea module for every `sourceSet`. Since querydsl plugin creates a sourceSet  named `querydsl` we get a module with that name, however, the modules do not seem to share classpaths.
When I wish to debug my application I can't because It won't build. 

Adding the `compile sourceSets.querydsl.output` line that should solve things fails since the sourceset does not exist at that point. It is added dynamically by the plugin.

My config looks like this.
````
querydsl {
    library = "com.mysema.querydsl:querydsl-apt:${queryDslVersion}"
    jpa = true
    querydslSourcesDir = "src/querydsl/java"
}
dependencies {
    compile sourceSets.querydsl.output
   ....
}
````

Note: this might be more appropriate on Idea bug list but I think it's also relevant here.

**Comment by holgerstolzenberg** [comment] 2016-03-23 13:40
Duplicate of #40.

**Closed by holgerstolzenberg** 2016-03-23 13:40 UTC
