### ISSUE TITLE
Dagger 2 plugin not downloading using buildscript

### ISSUE THREAD

**Issue by ben-manes** [ewerk/gradle-plugins#20] opened 2015-06-23 01:09 UTC
When using the buildscript notation the dagger plugin cannot be found, e.g. 

```bash
Could not find com.ewerk.gradle.plugins:dagger-plugin:1.0.0.
  Searched in the following locations:
    http://plugins.gradle.org/m2/com/ewerk/gradle/plugins/dagger-plugin/1.0.0/dagger-plugin-1.0.0.pom
    http://plugins.gradle.org/m2/com/ewerk/gradle/plugins/dagger-plugin/1.0.0/dagger-plugin-1.0.0.jar
    https://repo1.maven.org/maven2/com/ewerk/gradle/plugins/dagger-plugin/1.0.0/dagger-plugin-1.0.0.pom
    https://repo1.maven.org/maven2/com/ewerk/gradle/plugins/dagger-plugin/1.0.0/dagger-plugin-1.0.0.jar
```

The `plugins` notation works (as per the sample), but is problematic and incubating. It appears that jitpack.io cannot build the dagger plugin either, probably due to being confused by the shared repository.

It would be helpful if you published this to JCenter, enabled to sync automatically to the Gradle plugins repository.

**Comment by griffio** [comment] 2015-06-23 07:35
Can confirm - the list of plugins and versions is not up to date from the external repos.

When updated, I believe, a plugin script notation should be using the repository location at  "https://plugins.gradle.org/m2/" and not jcenter as in the sample Readme.

Could be when the change over to use "com.gradle.plugin-publish" was made?

Example of plugin using with plugins repo (https://plugins.gradle.org/m2/).
~~~
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }

  dependencies {
    classpath "com.ewerk.gradle.plugins:dagger-plugin:1.0.0"
  }
}
~~~

@holgerstolzenberg does this make sense?
* Plugins need to be updated in "https://plugins.gradle.org/m2/"
* Readme samples updated to use https://plugins.gradle.org/m2/ in buildscripts

**Comment by ben-manes** [comment] 2015-06-23 07:42
Using the plugin repository location doesn't work, for some unknown reason. The error message I posted used that (and a few others that I trimmed off). 

`https://plugins.gradle.org/m2/com/ewerk/gradle/plugins/dagger-plugin/1.0.0/dagger-plugin-1.0.0.pom` responds with a 404, though somehow Gradle can download with the plugin dsl.

My suggestion is to use the JCenter sync option for the maximum flexibility. When a new version is published to bintray, the artifact can be pushed to the plugin repository and maven central automatically.

**Comment by holgerstolzenberg** [comment] 2015-06-23 08:23
To be honest, I always try to use the `plugins` notation, as I do not like the old style. The publication process has changed some time ago and Bintray is not involved directly, as I publish to the Plugin Portal itself using a plugin provided by Gradle. I do not know how the publication is managed internally, it seems that Bintray is still involved somehow.

@ben-manes I can confirm that your example does not work, but the problem is that your maven coordinates are wrong. The Plugin Portals page for the dagger plugin shows examples on how to use the plugin with both syntax styles:

https://plugins.gradle.org/plugin/com.ewerk.gradle.plugins.dagger

As you can see, `gradle.plugin.` is prepended to the group id for some reason. That is nothing I forced and is somehow related to publication process internals, as the new syntax does not use this prefix.

Could you please try with the given example and give some feedback?

@griffio Yes the documentation needs some update.

**Comment by ben-manes** [comment] 2015-06-24 00:44
@holgerstolzenberg You're right that changing the groupId resolves the problem, but identified anther one. In its current form, it is [incompatible](https://github.com/ewerk/gradle-plugins/blob/master/dagger-plugin/src/main/groovy/com/ewerk/gradle/plugins/DaggerPlugin.groovy#L39) with the Android plugin. This is because it applies the `java` plugin.

Instead you should identify which plugin (java or android) is available and configure properly. You are welcome to borrow from my [jsonschema2pojo-gradle-plugin](https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/GenerateJsonSchemaTask.groovy#L44) which does this.

**Comment by griffio** [comment] 2015-06-24 07:34
I am happy to try and add this as I committed the Dagger plugin, if @holgerstolzenberg thinks its ok to support.  Most folks adopting Dagger2 would be Android.
Previously, I looked at the apt plugin https://bitbucket.org/hvisser/android-apt - that didn't support Java plugin use. There is a scenario mentioned there when a user's project wants annotation processing with both Java and Android modules.

**Comment by holgerstolzenberg** [comment] 2015-06-24 08:06
I am fine with that. I think this may be a problem for all of the plugins and maybe needs to be changed for  them all.

For me this raises the question whether this is some general design flaw? What do you guys think?

**Comment by griffio** [comment] 2015-06-24 13:33
I don't think it is flawed, there are just different audiences for each plugin. 
Autovalue and Dagger are the plugins that would attract Android users. Querydsl not so much.

The only 'competing' plugin is the generic https://bitbucket.org/hvisser/android-apt; but I like having specific plugins for libraries as there is less setup and noise (e.g. buildscript).

For example, I don't want any default output directory to be under ${projectDIr}build/classes as this causes problems with source not being visible and requires additional configuration with Intellij.

**Comment by holgerstolzenberg** [comment] 2015-06-25 09:33
Okay. I aggree.

@griffio Are you interested in providing the necessary PR?

**Comment by griffio** [comment] 2015-06-25 12:17
I am still looking into how to do this; but is it clear that Android plugins need different setup instead of  creating JavaCompile tasks (These configured in build variants). 

So, I will try over the weekend to create a PR for Dagger only.
Otherwise, I fail :( and will let you know.

**Closed** 2015-09-02 08:05 UTC
Labels: in progress, question
